### ISSUE TITLE
Arduino UNO Main - Function: Read pressure

### ISSUE THREAD

**Issue by ersve** [EricssonResearch/arms#30]
Main issue #29 

**Description**
Interrupt based function which map voltage from pressure sensor to Newton. The function should contain a option to state a threshold force that fires an interrupt / sets a flag when the sensor register forces above it. This to avoid polling in the Arduino UNO.

**Input**

- Threshold force

**Output**

- Current Force measured
- threshold flag ( TRUE/FALSE )

**Comment by Chryloz** [comment]
The pressure sensor is hooked up to a timer interrupt. It has two thresholds - one dynamically set by the rPi  (soft stop) and one static emergency stop (hard stop). The soft stop acts as an additional check that the motor does not simply follow the number of pulses but actually stops when the soft stop has been reached. This is not super accurate but helps avoiding gripping things very tight due to sending too many pulses when closing. The hard stop triggers a total shutdown of the gripper and it will no longer move by messages. This safeguard is in place in case the soft-stop limit is set too high. In order to resolve this, one must physically disconnect the sensor - then send message to clear the error flag - and then proceed to open the claw using a message again.
